<केंद्र><h1>अध्याय 1 प्रारंभिक ज्ञान</h1></केंद्र>

## 1. पायथन मूल बातें
### 1. सूची की समझ और सशर्त असाइनमेंट

संख्याओं का अनुक्रम बनाते समय, आप इसे 'पायथन' में इस प्रकार लिख सकते हैं:

In [1]:
L = []
def my_func(x):
    return 2*x
for i in range(5):
    L.append(my_func(i))
L

[0, 2, 4, 6, 8]

वास्तव में, आप लेखन को सरल बनाने के लिए सूची समझ का उपयोग कर सकते हैं: `[* for i in *]`। उनमें से, पहला `*` मैपिंग फ़ंक्शन है, और इसका इनपुट बाद में `i` द्वारा संदर्भित सामग्री है, और दूसरा `*` पुनरावृत्ति ऑब्जेक्ट का प्रतिनिधित्व करता है।

In [2]:
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

सूची अभिव्यक्तियाँ बहु-स्तरीय नेस्टिंग का भी समर्थन करती हैं, उदाहरण के लिए, निम्नलिखित उदाहरण में, पहला `फॉर` बाहरी लूप है, और दूसरा आंतरिक लूप है:

In [3]:
[m+'_'+n for m in ['a', 'b'] for n in ['c', 'd']]

['a_c', 'a_d', 'b_c', 'b_d']

सूची समझ के अलावा, एक अन्य उपयोगी वाक्यविन्यास चीनी 'if' चयन के साथ सशर्त असाइनमेंट है, जो 'मान = a यदि शर्त अन्यथा b' रूप लेता है:

In [4]:
value = 'cat' if 2>1 else 'dog'
value

'cat'

यह इस प्रकार लिखने के बराबर है:
```अजगर
ए, बी = 'बिल्ली', 'कुत्ता'
शर्त = 2 > 1 # इस समय यही सत्य है
यदि शर्त:
    मूल्य = ए
अन्य:
    मूल्य = बी
```

यहां सूची में 5 से अधिक तत्वों को छोटा करने का एक उदाहरण दिया गया है, अर्थात, 5 से अधिक तत्वों को 5 से बदलें, और 5 से कम मूल मान बनाए रखें:

In [5]:
L = [1, 2, 3, 4, 5, 6, 7]
[i if i <= 5 else 5 for i in L]

[1, 2, 3, 4, 5, 5, 5]

### 2. अनाम फ़ंक्शन और मानचित्र विधियाँ

कुछ फ़ंक्शंस की परिभाषा में स्पष्ट और सरल मैपिंग संबंध होता है, जैसे कि उपरोक्त `my_func` फ़ंक्शन, इस समय, इसे अनाम फ़ंक्शन विधि का उपयोग करके संक्षिप्त रूप से व्यक्त किया जा सकता है:

In [6]:
my_func = lambda x: 2*x
my_func(3)

6

In [7]:
multi_para_func = lambda a, b: a + b
multi_para_func(1, 2) 

3

लेकिन उपरोक्त उपयोग वास्तव में "गुमनाम" के अर्थ का उल्लंघन करता है, वास्तव में, इसका उपयोग अक्सर उन स्थितियों में किया जाता है जहां एकाधिक कॉल की आवश्यकता नहीं होती है, उदाहरण के लिए उपरोक्त सूची समझ में, उपयोगकर्ता को नाम की परवाह नहीं है फ़ंक्शन, लेकिन केवल मैपिंग संबंध की परवाह करता है:

In [8]:
[(lambda x: 2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

उपर्युक्त सूची व्युत्पत्ति अनाम फ़ंक्शन मैपिंग के लिए, इसे पूरा करने के लिए `पाइथन` में `मैप` फ़ंक्शन प्रदान किया गया है, यह एक `मैप` ऑब्जेक्ट लौटाता है, जिसे `सूची` के माध्यम से एक सूची में परिवर्तित करने की आवश्यकता है:

In [9]:
list(map(lambda x: 2*x, range(5)))

[0, 2, 4, 6, 8]

एकाधिक इनपुट मानों की फ़ंक्शन मैपिंग के लिए, इसे पुनरावृत्ति ऑब्जेक्ट जोड़कर प्राप्त किया जा सकता है:

In [10]:
list(map(lambda x, y: str(x)+'_'+y, range(5), list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

### 3. ज़िप ऑब्जेक्ट और गणना विधि

`ज़िप` फ़ंक्शन कई पुनरावृत्त वस्तुओं को टुपल्स से बनी एक पुनरावृत्त वस्तु में पैक कर सकता है, यह एक `ज़िप` ऑब्जेक्ट लौटाता है, और संबंधित पैकेजिंग परिणाम `टुपल` और `सूची` के माध्यम से प्राप्त किए जा सकते हैं:

In [11]:
L1, L2, L3 = list('abc'), list('def'), list('hij')
list(zip(L1, L2, L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [12]:
tuple(zip(L1, L2, L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

`ज़िप` फ़ंक्शन का उपयोग अक्सर लूप पुनरावृत्ति के दौरान किया जाता है:

In [13]:
for i, j, k in zip(L1, L2, L3):
     print(i, j, k)

a d h
b e i
c f j


`एन्यूमरेट` एक विशेष पैकेज है जो पुनरावृत्ति के दौरान पुनरावृत्त तत्वों के ट्रैवर्सल अनुक्रम संख्या को बांध सकता है:

In [14]:
L = list('abcd')
for index, value in enumerate(L):
     print(index, value)

0 a
1 b
2 c
3 d


इस फ़ंक्शन को `ज़िप` ऑब्जेक्ट का उपयोग करके भी आसानी से कार्यान्वित किया जा सकता है:

In [15]:
for index, value in zip(range(len(L)), L):
     print(index, value)

0 a
1 b
2 c
3 d


जब आपको दो सूचियों के बीच शब्दकोश मैपिंग स्थापित करने की आवश्यकता होती है, तो आप `ज़िप` ऑब्जेक्ट का उपयोग कर सकते हैं:

In [16]:
dict(zip(L1, L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

अब चूँकि एक संपीड़न फ़ंक्शन है, `पायथन` डीकंप्रेसन ऑपरेशन करने के लिए संयुक्त उपयोग के लिए `*` ऑपरेटर और `ज़िप` भी प्रदान करता है:

In [17]:
zipped = list(zip(L1, L2, L3))
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [18]:
list(zip(*zipped)) # 三个元组分别对应原来的列表

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

## 2. सुन्न मूल बातें
### 1. एनपी सारणी का निर्माण
सबसे सामान्य विधि इसे `सरणी` के माध्यम से बनाना है:

In [19]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

निम्नलिखित चर्चा करता है कि कुछ विशेष सरणियाँ कैसे उत्पन्न करें:

【a】अंकगणित अनुक्रम: `np.linspace`, `np.arange`

In [20]:
np.linspace(1,5,11) # 起始、终止（包含）、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [21]:
np.arange(1,5,2) # 起始、终止（不包含）、步长

array([1, 3])

【बी】विशेष आव्यूह: `शून्य`, `आंख`, `पूर्ण`

In [22]:
np.zeros((2,3)) # 传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(3) # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3, k=1) # 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [25]:
np.full((2,3), 10) # 元组传入大小，10表示填充数值

array([[10, 10, 10],
       [10, 10, 10]])

In [26]:
np.full((2,3), [1,2,3]) # 每行填入相同的列表

array([[1, 2, 3],
       [1, 2, 3]])

【सी】रैंडम मैट्रिक्स: `np.random`

सबसे अधिक उपयोग किए जाने वाले यादृच्छिक पीढ़ी फ़ंक्शन `रैंड`, `रैंडन`, `रैंडिंट`, `चॉइस` हैं, जो क्रमशः 0-1 समान रूप से वितरित यादृच्छिक सरणी, मानक सामान्य यादृच्छिक सरणी, यादृच्छिक पूर्णांक समूह और यादृच्छिक सूची नमूनाकरण का प्रतिनिधित्व करते हैं:

In [27]:
np.random.rand(3) # 生成服从0-1均匀分布的三个随机数

array([0.92340835, 0.20019461, 0.40755472])

In [28]:
np.random.rand(3, 3) # 注意这里传入的不是元组，每个维度大小分开输入

array([[0.8012362 , 0.53154881, 0.05858554],
       [0.13103034, 0.18108091, 0.30253153],
       [0.00528884, 0.99402007, 0.36348797]])

अंतराल `a` से `b` का पालन करते हुए एक समान वितरण के लिए, इसे निम्नानुसार उत्पन्न किया जा सकता है:

In [29]:
a, b = 5, 15
(b - a) * np.random.rand(3) + a

array([6.59370831, 8.03865138, 9.19172546])

आम तौर पर, आप मौजूदा लाइब्रेरी फ़ंक्शंस चुन सकते हैं:

In [30]:
np.random.uniform(5, 15, 3)

array([11.26499636, 13.12311185,  6.00774156])

`randn` `N(0,I)` का मानक सामान्य वितरण उत्पन्न करता है:

In [31]:
np.random.randn(3)

array([ 1.87000209,  1.19885561, -0.58802943])

In [32]:
np.random.randn(2, 2)

array([[-1.3642839 , -0.31497567],
       [-1.9452492 , -3.17272882]])

भिन्नता $\sigma^2$ और माध्य $\mu$ के साथ एक अविभाज्य सामान्य वितरण के लिए, इसे निम्नानुसार उत्पन्न किया जा सकता है:

In [33]:
sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma

array([1.56024917, 0.22829486, 7.3764211 ])

इसी तरह, आप इसे किसी मौजूदा फ़ंक्शन से जेनरेट करना भी चुन सकते हैं:

In [34]:
np.random.normal(3, 2.5, 3)

array([3.53517851, 5.3441269 , 3.51192744])

`रैंडिंट` उत्पन्न यादृच्छिक पूर्णांक का न्यूनतम, अधिकतम (अनन्य) मान और आयाम आकार निर्दिष्ट कर सकता है:

In [35]:
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
np.random.randint(low, high, size)

array([[ 5, 12],
       [14,  9]])

`पसंद` एक निश्चित संभावना और विधि के साथ दी गई सूची से परिणाम निकाल सकता है, जब संभावना निर्दिष्ट नहीं होती है, तो यह एक समान नमूनाकरण है। डिफ़ॉल्ट निष्कर्षण विधि प्रतिस्थापन के साथ नमूनाकरण है।

In [36]:
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['b', 'a'], dtype='<U1')

In [37]:
np.random.choice(my_list, (3,3))

array([['c', 'b', 'd'],
       ['d', 'a', 'd'],
       ['a', 'c', 'd']], dtype='<U1')

जब लौटाए गए तत्वों की संख्या मूल सूची के समान होती है, तो प्रतिस्थापन के बिना नमूनाकरण 'क्रमपरिवर्तन' फ़ंक्शन का उपयोग करने के बराबर होता है, यानी मूल सूची को तोड़ना:

In [38]:
np.random.permutation(my_list)

array(['c', 'a', 'd', 'b'], dtype='<U1')

अंत में, जिस चीज़ का उल्लेख करने की आवश्यकता है वह यादृच्छिक बीज है, जो यादृच्छिक संख्याओं के आउटपुट को ठीक कर सकता है:

In [39]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [40]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

### 2. एनपी सरणियों का परिवर्तन और विलय
【ए】ट्रांसपोज़: `टी`

In [41]:
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

【बी】मर्ज ऑपरेशन: `r_`, `c_`

द्वि-आयामी सरणियों के लिए, `r_` और `c_` क्रमशः ऊपरी और निचले विलय और बाएँ और दाएँ विलय का प्रतिनिधित्व करते हैं:

In [42]:
np.r_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

एक-आयामी सरणियों और दो-आयामी सरणियों को विलय करते समय, उन्हें कॉलम वैक्टर के रूप में माना जाना चाहिए, यदि लंबाई मेल खाती है, तो केवल बाएं और दाएं विलय के `c_` ऑपरेशन का उपयोग किया जा सकता है:

In [44]:
try:
     np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
     Err_Msg = e
Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [45]:
np.r_[np.array([0,0]),np.zeros(2)]

array([0., 0., 0., 0.])

In [46]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

【सी】आयाम परिवर्तन: `रीशेप`

`रीशेप` उपयोगकर्ताओं को नए आयामों के अनुसार मूल सरणी को पुनर्व्यवस्थित करने में मदद कर सकता है। उपयोग में दो मोड हैं, अर्थात् `सी` मोड और `एफ` मोड, जो क्रमशः पंक्ति-दर-पंक्ति और कॉलम-दर-कॉलम क्रम में भरे और पढ़े जाते हैं।

In [47]:
target = np.arange(8).reshape(2,4)
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
target.reshape((4,2), order='C') # 按照行读取和填充

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [49]:
target.reshape((4,2), order='F') # 按照列读取和填充

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

विशेष रूप से, चूंकि बुलाए गए सरणी का आकार नियतात्मक है, `रीशेप` एक आयाम को खाली रखने की अनुमति देता है, जिस स्थिति में इसे केवल -1 से भरने की आवश्यकता होती है:

In [50]:
target.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

`n*1` आकार की सरणी को 1-आयामी सरणी में बदलने के लिए निम्नलिखित ऑपरेशन का आमतौर पर उपयोग किया जाता है:

In [51]:
target = np.ones((3,1))
target

array([[1.],
       [1.],
       [1.]])

In [52]:
target.reshape(-1)

array([1., 1., 1.])

### 3. एनपी सरणी की स्लाइसिंग और इंडेक्सिंग
सरणी स्लाइसिंग मोड 'स्लाइस' प्रकार के 'स्टार्ट:एंड:स्टेप' स्लाइसिंग का समर्थन करता है, और आप स्लाइसिंग के लिए एक निश्चित आयाम के सूचकांक को निर्दिष्ट करने के लिए सीधे सूची में भी पास कर सकते हैं:

In [53]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
target[:-1, [0,2]]

array([[0, 2],
       [3, 5]])

इसके अलावा, आप संबंधित आयामों पर बूलियन इंडेक्स का उपयोग करने के लिए `np.ix_` का भी उपयोग कर सकते हैं, लेकिन इस समय `स्लाइस` स्लाइस का उपयोग नहीं किया जा सकता है:

In [55]:
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [56]:
target[np.ix_([1,2], [True, False, True])]

array([[3, 5],
       [6, 8]])

जब सरणी आयाम 1 आयाम होता है, तो बूलियन अनुक्रमण सीधे `np.ix_` के बिना किया जा सकता है:

In [57]:
new = target.reshape(-1)
new[new%2==0]

array([0, 2, 4, 6, 8])

### 4. आमतौर पर उपयोग किए जाने वाले फ़ंक्शन
सरलता के लिए, यह माना जाता है कि निम्नलिखित कार्यों के लिए इनपुट सरणियाँ सभी एक-आयामी हैं।

【ए】`कहां`

`कहां` एक सशर्त फ़ंक्शन है जो उस स्थिति के अनुरूप भरने का मूल्य निर्दिष्ट कर सकता है जहां शर्त पूरी होती है और वह स्थिति जहां शर्त पूरी नहीं होती है:

In [58]:
a = np.array([-1,1,-1,0])
np.where(a>0, a, 5) # 对应位置为True时填充a对应元素，否则填充5

array([5, 1, 5, 5])

【बी】`नॉनजीरो`, `आर्गमैक्स`, `आर्गमिन`

ये तीन फ़ंक्शन इंडेक्स लौटाते हैं। `नॉनजीरो` गैर-शून्य संख्याओं का इंडेक्स लौटाता है। `argmax` और `argmin` क्रमशः सबसे बड़ी और सबसे छोटी संख्याओं का इंडेक्स लौटाता है:

In [59]:
a = np.array([-2,-5,0,1,3,-1])
np.nonzero(a)

(array([0, 1, 3, 4, 5], dtype=int64),)

In [60]:
a.argmax()

4

In [61]:
a.argmin()

1

【सी】`कोई भी`, `सभी`

`any` का अर्थ है `True` लौटाना जब अनुक्रम में कम से कम **एक** `True` या गैर-शून्य तत्व हो, अन्यथा यह `False` लौटाता है

`सभी` का अर्थ है `सही` लौटाना जब अनुक्रम तत्व सभी `सही` या गैर-शून्य तत्व हों, अन्यथा यह `गलत` लौटाता है

In [62]:
a = np.array([0,1])
a.any()

True

In [63]:
 a.all()

False

【d】`cumprod`, `cumsum`, `diff`

`cumprod` और `cumsum` क्रमशः संचयी गुणन और संचय कार्यों का प्रतिनिधित्व करते हैं, समान लंबाई के रिटर्निंग सरणियाँ। `diff` पिछले तत्व से अंतर का प्रतिनिधित्व करता है, क्योंकि पहला तत्व एक लापता मान है, डिफ़ॉल्ट मापदंडों के तहत, लंबाई है क्या मूल सरणी शून्य से 1 है?

In [64]:
a = np.array([1,2,3])
a.cumprod()

array([1, 2, 6], dtype=int32)

In [65]:
a.cumsum()

array([1, 3, 6], dtype=int32)

In [66]:
np.diff(a)

array([1, 1])

【ई】सांख्यिकीय कार्य

आमतौर पर उपयोग किए जाने वाले सांख्यिकीय कार्यों में `अधिकतम, न्यूनतम, माध्य, माध्यिका, एसटीडी, var, योग, क्वांटाइल` शामिल हैं, जिनमें से क्वांटाइल गणना एक वैश्विक विधि है, इसलिए इसे `array.quantile` विधि के माध्यम से नहीं बुलाया जा सकता है:

In [67]:
target = np.arange(5)
target

array([0, 1, 2, 3, 4])

In [68]:
target.max()

4

In [69]:
np.quantile(target, 0.5) # 0.5分位数

2.0

लेकिन लुप्त मानों वाले सरणियों के लिए, वे जो परिणाम लौटाते हैं वे भी लुप्त मान हैं। यदि आपको लुप्त मानों को छोड़ना है, तो आपको `nan*` प्रकार के फ़ंक्शन का उपयोग करना होगा।

In [70]:
target = np.array([1, 2, np.nan])
target

array([ 1.,  2., nan])

In [71]:
target.max()

nan

In [72]:
np.nanmax(target)

2.0

In [73]:
np.nanquantile(target, 0.5)

1.5

सहप्रसरण और सहसंबंध गुणांक की गणना क्रमशः `cov, corrcoef` का उपयोग करके की जा सकती है:

In [74]:
target1 = np.array([1,3,5,9])
target2 = np.array([1,5,3,-9])
np.cov(target1, target2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [75]:
np.corrcoef(target1, target2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

अंत में, द्वि-आयामी `नम्पी` सरणी में सांख्यिकीय फ़ंक्शन के `अक्ष` पैरामीटर की व्याख्या करना आवश्यक है। यह एक निश्चित आयाम में सांख्यिकीय विशेषताओं की गणना कर सकता है, परिणाम सांख्यिकीय सूचकांक है जब `axis=1` `कॉलम का परिणाम पंक्ति का एक सांख्यिकीय संकेतक होता है:

In [76]:
target = np.arange(1,10).reshape(3,-1)
target

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
target.sum(0)

array([12, 15, 18])

In [78]:
target.sum(1)

array([ 6, 15, 24])

### 5. प्रसारण तंत्र

प्रसारण तंत्र का उपयोग विभिन्न आयामों के दो सरणियों के बीच संचालन को संभालने के लिए किया जाता है। यहां हम केवल दो से अधिक आयामों वाले सरणियों के लिए प्रसारण तंत्र पर चर्चा करते हैं।

【ए】स्केलर और सरणी संचालन

जब एक स्केलर को किसी सरणी पर संचालित किया जाता है, तो स्केलर स्वचालित रूप से सरणी के आकार तक विस्तारित हो जाता है, और फिर तत्व-दर-तत्व ऑपरेशन किया जाता है:

In [79]:
res = 3 * np.ones((2,2)) + 1
res

array([[4., 4.],
       [4., 4.]])

In [80]:
res = 1 / res
res

array([[0.25, 0.25],
       [0.25, 0.25]])

【बी】द्वि-आयामी सरणियों के बीच संचालन

जब दो सरणियों के आयाम बिल्कुल समान हों, तो संबंधित तत्व के संचालन का उपयोग करें, अन्यथा एक त्रुटि की सूचना दी जाएगी, जब तक कि किसी एक सरणियों का आयाम $m×1$ या $1×n$ न हो, तो आयाम $1$ के साथ दूसरे तक विस्तारित किया जाएगा। एक सरणी आयाम के आकार से मेल खाती है। उदाहरण के लिए, $1×2$ सरणियों और $3×2$ सरणियों पर तत्व-दर-तत्व संचालन करते समय, पहले सरणी को $3×2$ तक विस्तारित किया जाएगा, और विस्तार के दौरान संबंधित मान निर्दिष्ट किए जाएंगे। हालाँकि, यह ध्यान दिया जाना चाहिए कि यदि पहली सरणी का आयाम $1×3$ है, तो एक त्रुटि की सूचना दी जाएगी क्योंकि दूसरे आयाम का आकार मेल नहीं खाता है और $1$ नहीं है।

In [81]:
res = np.ones((3,2))
res

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [82]:
res * np.array([[2,3]]) # 第二个数组扩充第一维度为3

array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [83]:
res * np.array([[2],[3],[4]]) # 第二个数组扩充第二维度为2

array([[2., 2.],
       [3., 3.],
       [4., 4.]])

In [84]:
res * np.array([[2]]) # 等价于两次扩充，第二个数组两个维度分别扩充为3和2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

[सी] एक-आयामी सरणियों और दो-आयामी सरणियों पर संचालन

जब एक-आयामी सरणी $A_k$ द्वि-आयामी सरणी $B_{m,n}$ पर संचालित होती है, तो यह एक-आयामी सरणी को $A_{1,k}$ की द्वि-आयामी सरणी के रूप में मानने के बराबर है। उपयोग किया गया प्रसारण नियम वही है जो [ b] उपरोक्त के अनुरूप है। जब $k!=n$ और न ही $k और न ही n$ $1$ है, तो एक त्रुटि की सूचना दी जाएगी।

In [85]:
np.ones(3) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [86]:
np.ones(3) + np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [87]:
np.ones(1) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

### 6. सदिशों और आव्यूहों की गणना
【ए】वेक्टर आंतरिक उत्पाद: `डॉट`

$$\rm \mathbf{a}\cdot\mathbf{b} = \sum_ia_ib_i$$

In [88]:
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)

22

【बी】वेक्टर मानदंड और मैट्रिक्स मानदंड: `np.linalg.norm`

मैट्रिक्स मानदंड की गणना में, सबसे महत्वपूर्ण बात 'ऑर्ड' पैरामीटर है, वैकल्पिक मान इस प्रकार हैं:

|.ऑर्ड |.आव्यूहों के लिए मानदंड |. सदिशों के लिए मानदंड |
|. :--- |. ----: |
|. कोई नहीं |. फ्रोबेनियस मानदंड |
|. 'फ्रॉ' |. फ्रोबेनियस मानदंड |
|. 'एनयूसी' |. परमाणु मानक |
|. जानकारी |. अधिकतम(योग(एबीएस(x), अक्ष=1)) |
|. -inf |. मिनट(योग(एबीएस(x), अक्ष=1)) |
|. 0 | / |. योग(x != 0) |
|. 1 |. अधिकतम(योग(abs(x), अक्ष=0) |
| -1 | मिनट(योग(एबीएस(एक्स), अक्ष=0) |
|.2 |.2-मानदंड (सबसे बड़ा मान) |
| -2 |. सबसे छोटा एकवचनमूल्य | नीचे के रूप में |
|. अन्य | / |. sum(abs(x)\*\*ord)\*\*(1./ord) |

In [89]:
matrix_target =  np.arange(4).reshape(-1,2)
matrix_target

array([[0, 1],
       [2, 3]])

In [90]:
np.linalg.norm(matrix_target, 'fro')

3.7416573867739413

In [91]:
np.linalg.norm(matrix_target, np.inf)

5.0

In [92]:
np.linalg.norm(matrix_target, 2)

3.702459173643833

In [93]:
vector_target =  np.arange(4)
vector_target

array([0, 1, 2, 3])

In [94]:
np.linalg.norm(vector_target, np.inf)

3.0

In [95]:
np.linalg.norm(vector_target, 2)

3.7416573867739413

In [96]:
np.linalg.norm(vector_target, 3)

3.3019272488946263

【सी】मैट्रिक्स गुणन: `@`

$$\rm [\mathbf{A}_{m\times p}\mathbf{B}_{p\times n}]_{ij} = \sum_{k=1}^p\mathbf{A}_ {ik}\mathbf{B}_{kj}$$

In [97]:
a = np.arange(4).reshape(-1,2)
a

array([[0, 1],
       [2, 3]])

In [98]:
b = np.arange(-4,0).reshape(-1,2)
b

array([[-4, -3],
       [-2, -1]])

In [99]:
a@b

array([[ -2,  -1],
       [-14,  -9]])

## 3. अभ्यास
### Ex1: मैट्रिक्स गुणन लिखने के लिए सूची समझ का उपयोग करें
सूत्र के अनुसार, सामान्य मैट्रिक्स गुणन को ट्रिपल लूप द्वारा लिखा जा सकता है। कृपया इसे सूची समझ के रूप में फिर से लिखें।

In [100]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
(np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差

True

### Ex2: अद्यतन मैट्रिक्स
मैट्रिक्स $A_{m×n}$ मान लें, अब मैट्रिक्स $B$ उत्पन्न करने के लिए प्रत्येक तत्व को $A$ में अपडेट करें, अपडेट विधि $B_{ij}=A_{ij}\sum_{k=1}^ n\ है frac{1}{A_{ik}}$, उदाहरण के लिए, निम्नलिखित मैट्रिक्स $A$ है, तो $B_{2,2}=5\times(\frac{1}{4}+\frac{ 1} {5}+\frac{1}{6})=\frac{37}{12}$, कृपया इसे कुशलतापूर्वक लागू करने के लिए `Numpy` का उपयोग करें।
$$\begin{split}A=\left[ \begin{matrix} 1 & 2 &3\\4&5&6\\7&8&9 \end{matrix} \right]\end{split}$$

### Ex3: ची-स्क्वायर आँकड़ा

मैट्रिक्स $A_{m\times n}$ मान लें, $B_{ij} = \frac{(\sum_{i=1}^mA_{ij})\times (\sum_{j=1}^nA_{ij) को निरूपित करें })}{\sum_{i=1}^m\sum_{j=1}^nA_{ij}}$, ची-स्क्वायर मान को इस प्रकार परिभाषित करें:
$$\chi^2 = \sum_{i=1}^m\sum_{j=1}^n\frac{(A_{ij}-B_{ij})^2}{B_{ij}}$$
कृपया दिए गए मैट्रिक्स $A$ के लिए $\chi^2$ की गणना करने के लिए `Numpy` का उपयोग करें

In [101]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))

### Ex4: मैट्रिक्स गणनाओं का बेहतर प्रदर्शन
मान लीजिए $Z$ $m×n$ का आव्यूह है, $B$ और $U$ क्रमशः $m×p$ और $p×n$ का आव्यूह है, $B_i$ $ की $i$वीं पंक्ति है B$, $U_j$, $U$ का $j$वां कॉलम है। निम्नलिखित $\displaystyle R=\sum_{i=1}^m\sum_{j=1}^n\|B_i-U_j\ को परिभाषित करता है। |_2^2Z_{ ij}$, जहां $\|\mathbf{a}\|_2^2$ वेक्टर $a$ $\sum_i a_i^2$ के वर्ग घटकों के योग का प्रतिनिधित्व करता है।

यदि कोई अब नीचे दिए गए नमूना डेटा के आधार पर $R$ के मूल्य की गणना करता है, तो कृपया इस समस्या के आधार पर इस कोड के प्रदर्शन को बेहतर बनाने के लिए 'Numpy' में फ़ंक्शन का पूरा उपयोग करें।

In [102]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i]-U[:,j])**2).sum()
            L_res.append(norm_value*Z[i][j])
    return sum(L_res)
solution(B, U, Z)

100566

### Ex5: क्रमागत पूर्णांकों की अधिकतम लंबाई

पूर्णांकों की एक `नम्पी` सरणी इनपुट करें और बढ़ती दिशा को संदर्भित करते हुए आगे की दिशा के साथ सख्ती से बढ़ती लगातार पूर्णांक उपसरणी की अधिकतम लंबाई लौटाएं। उदाहरण के लिए, इनपुट \[1,2,5,6,7\], \[5,6,7\] अधिकतम लंबाई के साथ एक सतत पूर्णांक उपसरणी है, इसलिए आउटपुट 3 है; 1,2 ,3,4,6\], \[1,2,3,4\] अधिकतम लंबाई के साथ सतत पूर्णांक उपसरणी हैं, इसलिए 4 आउटपुट है। कृपया `नम्पी` के अंतर्निहित कार्यों का पूरा उपयोग करें। (टिप: `नॉनजीरो, डिफ` फ़ंक्शन का उपयोग करने पर विचार करें)