<center><h1>Chapter 1 Preliminary Knowledge</h1></center>

## 1. Python Basics
### 1. List derivation and conditional assignment

When generating a sequence of numbers, it can be written in `Python` as follows:

In [1]:
L = []
def my_func(x):
    return 2*x
for i in range(5):
    L.append(my_func(i))
L

[0, 2, 4, 6, 8]

In fact, we can use list derivation to simplify the writing: `[* for i in *]`. Among them, the first `*` is the mapping function, whose input is the content referred to by the following `i`, and the second `*` represents the iterated object.

In [2]:
[my_func(i) for i in range(5)]

[0, 2, 4, 6, 8]

List expressions also support multi-layer nesting. For example, in the following example, the first `for` is the outer loop and the second is the inner loop:

In [3]:
[m+'_'+n for m in ['a', 'b'] for n in ['c', 'd']]

['a_c', 'a_d', 'b_c', 'b_d']

In addition to list comprehensions, another useful syntax sugar is conditional assignment with an `if` choice, in the form of `value = a if condition else b`:

In [4]:
value = 'cat' if 2>1 else 'dog'
value

'cat'

Equivalent to the following:
```python
a, b = 'cat', 'dog'
condition = 2 > 1 # True at this time
if condition:
value = a
else:
value = b
```

Here is an example to truncate the elements in the list that are larger than 5, that is, replace them with 5, and keep the original values ​​if they are smaller than 5:

In [5]:
L = [1, 2, 3, 4, 5, 6, 7]
[i if i <= 5 else 5 for i in L]

[1, 2, 3, 4, 5, 5, 5]

### 2. Anonymous functions and map methods

Some function definitions have clear and simple mapping relationships, such as the `my_func` function above. In this case, anonymous functions can be used to concisely represent them:

In [6]:
my_func = lambda x: 2*x
my_func(3)

6

In [7]:
multi_para_func = lambda a, b: a + b
multi_para_func(1, 2) 

3

However, the above usage actually violates the meaning of "anonymous". In fact, it is often used in situations where multiple calls are not required. For example, in the example of the list derivation above, the user does not care about the name of the function, but only cares about the mapping relationship:

In [8]:
[(lambda x: 2*x)(i) for i in range(5)]

[0, 2, 4, 6, 8]

For the above-mentioned list-derived anonymous function mapping, `Python` provides the `map` function to complete it. It returns a `map` object, which needs to be converted to a list through `list`:

In [9]:
list(map(lambda x: 2*x, range(5)))

[0, 2, 4, 6, 8]

For function mapping of multiple input values, it can be implemented by appending iterable objects:

In [10]:
list(map(lambda x, y: str(x)+'_'+y, range(5), list('abcde')))

['0_a', '1_b', '2_c', '3_d', '4_e']

### 3. zip object and enumerate method

The `zip` function can package multiple iterable objects into an iterable object consisting of a tuple. It returns a `zip` object. The corresponding packaged result can be obtained through `tuple` and `list`:

In [11]:
L1, L2, L3 = list('abc'), list('def'), list('hij')
list(zip(L1, L2, L3))

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [12]:
tuple(zip(L1, L2, L3))

(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))

The `zip` function is often used when looping:

In [13]:
for i, j, k in zip(L1, L2, L3):
     print(i, j, k)

a d h
b e i
c f j


`enumerate` is a special package that can bind the traversal index of the iterated elements during iteration:

In [14]:
L = list('abcd')
for index, value in enumerate(L):
     print(index, value)

0 a
1 b
2 c
3 d


This functionality can also be easily achieved using the zip object:

In [15]:
for index, value in zip(range(len(L)), L):
     print(index, value)

0 a
1 b
2 c
3 d


When you need to create a dictionary mapping between two lists, you can use the `zip` object:

In [16]:
dict(zip(L1, L2))

{'a': 'd', 'b': 'e', 'c': 'f'}

Now that there is a compression function, `Python` also provides the `*` operator and `zip` to perform decompression operations:

In [17]:
zipped = list(zip(L1, L2, L3))
zipped

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]

In [18]:
list(zip(*zipped)) # 三个元组分别对应原来的列表

[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]

## 2. Numpy Basics
### 1. Construction of np array
The most common method is to construct it through `array`:

In [19]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

The following discusses some special array generation methods:

[a] Arithmetic sequence: `np.linspace`, `np.arange`

In [20]:
np.linspace(1,5,11) # 起始、终止（包含）、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [21]:
np.arange(1,5,2) # 起始、终止（不包含）、步长

array([1, 3])

【b】Special matrices: `zeros`, `eye`, `full`

In [22]:
np.zeros((2,3)) # 传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(3) # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3, k=1) # 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [25]:
np.full((2,3), 10) # 元组传入大小，10表示填充数值

array([[10, 10, 10],
       [10, 10, 10]])

In [26]:
np.full((2,3), [1,2,3]) # 每行填入相同的列表

array([[1, 2, 3],
       [1, 2, 3]])

【c】Random matrix: `np.random`

The most commonly used random generation functions are `rand`, `randn`, `randint`, `choice`, which represent 0-1 uniformly distributed random arrays, standard normal random arrays, random integer groups, and random list sampling respectively:

In [27]:
np.random.rand(3) # 生成服从0-1均匀分布的三个随机数

array([0.92340835, 0.20019461, 0.40755472])

In [28]:
np.random.rand(3, 3) # 注意这里传入的不是元组，每个维度大小分开输入

array([[0.8012362 , 0.53154881, 0.05858554],
       [0.13103034, 0.18108091, 0.30253153],
       [0.00528884, 0.99402007, 0.36348797]])

A uniform distribution on the interval `a` to `b` can be generated as follows:

In [29]:
a, b = 5, 15
(b - a) * np.random.rand(3) + a

array([6.59370831, 8.03865138, 9.19172546])

Generally, you can choose existing library functions:

In [30]:
np.random.uniform(5, 15, 3)

array([11.26499636, 13.12311185,  6.00774156])

`randn` generates a standard normal distribution of `N(0,I)`:

In [31]:
np.random.randn(3)

array([ 1.87000209,  1.19885561, -0.58802943])

In [32]:
np.random.randn(2, 2)

array([[-1.3642839 , -0.31497567],
       [-1.9452492 , -3.17272882]])

A univariate normal distribution with variance $\sigma^2$ and mean $\mu$ can be generated as follows:

In [33]:
sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma

array([1.56024917, 0.22829486, 7.3764211 ])

Similarly, you can choose to generate from an existing function:

In [34]:
np.random.normal(3, 2.5, 3)

array([3.53517851, 5.3441269 , 3.51192744])

`randint` can specify the minimum and maximum (exclusive) values ​​and dimensions of the generated random integers:

In [35]:
low, high, size = 5, 15, (2,2) # 生成5到14的随机整数
np.random.randint(low, high, size)

array([[ 5, 12],
       [14,  9]])

`choice` can extract results from a given list with a certain probability and method. When the probability is not specified, uniform sampling is used. The default extraction method is sampling with replacement:

In [36]:
my_list = ['a', 'b', 'c', 'd']
np.random.choice(my_list, 2, replace=False, p=[0.1, 0.7, 0.1 ,0.1])

array(['b', 'a'], dtype='<U1')

In [37]:
np.random.choice(my_list, (3,3))

array([['c', 'b', 'd'],
       ['d', 'a', 'd'],
       ['a', 'c', 'd']], dtype='<U1')

When the number of elements returned is the same as the original list, sampling without replacement is equivalent to using the `permutation` function, which breaks up the original list:

In [38]:
np.random.permutation(my_list)

array(['c', 'a', 'd', 'b'], dtype='<U1')

Finally, it is important to mention the random seed, which can fix the output of random numbers:

In [39]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [40]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

### 2. Transformation and merging of np arrays
【a】Transpose: `T`

In [41]:
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

【b】Merge operation: `r_`, `c_`

For a two-dimensional array, `r_` and `c_` represent top-bottom merge and left-right merge respectively:

In [42]:
np.r_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

When merging a one-dimensional array and a two-dimensional array, they should be treated as column vectors, and only the left-right merge `c_` operation can be used when the lengths match:

In [44]:
try:
     np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
     Err_Msg = e
Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [45]:
np.r_[np.array([0,0]),np.zeros(2)]

array([0., 0., 0., 0.])

In [46]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

【c】Dimension transformation: `reshape`

`reshape` can help users rearrange the original array according to the new dimension. There are two modes when using it, namely `C` mode and `F` mode, which fill and read in row-by-row and column-by-column order respectively.

In [47]:
target = np.arange(8).reshape(2,4)
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
target.reshape((4,2), order='C') # 按照行读取和填充

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [49]:
target.reshape((4,2), order='F') # 按照列读取和填充

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In particular, since the size of the called array is fixed, `reshape` allows one dimension to be vacant, and it can be filled with -1:

In [50]:
target.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

The following operation of converting an array of size `n*1` to a 1-dimensional array is often used:

In [51]:
target = np.ones((3,1))
target

array([[1.],
       [1.],
       [1.]])

In [52]:
target.reshape(-1)

array([1., 1., 1.])

### 3. Slicing and indexing of np arrays
The array slicing mode supports slicing using the `slice` type of `start:end:step`, and you can also directly pass in a list to specify the index of a certain dimension for slicing:

In [53]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
target[:-1, [0,2]]

array([[0, 2],
       [3, 5]])

In addition, you can use boolean indexing on the corresponding dimensions using np.ix_, but you cannot use slice slicing at this time:

In [55]:
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [56]:
target[np.ix_([1,2], [True, False, True])]

array([[3, 5],
       [6, 8]])

When the array dimension is 1-dimensional, boolean indexing can be done directly without `np.ix_`:

In [57]:
new = target.reshape(-1)
new[new%2==0]

array([0, 2, 4, 6, 8])

### 4. Common functions
For simplicity, it is assumed that the arrays input to the following functions are all one-dimensional.

[a] `where`

`where` is a conditional function that can specify the fill values ​​corresponding to the positions that meet the conditions and do not meet the conditions:

In [58]:
a = np.array([-1,1,-1,0])
np.where(a>0, a, 5) # 对应位置为True时填充a对应元素，否则填充5

array([5, 1, 5, 5])

【b】`nonzero`, `argmax`, `argmin`

These three functions return indices. `nonzero` returns the index of non-zero numbers, and `argmax` and `argmin` return the index of the maximum and minimum numbers respectively:

In [59]:
a = np.array([-2,-5,0,1,3,-1])
np.nonzero(a)

(array([0, 1, 3, 4, 5], dtype=int64),)

In [60]:
a.argmax()

4

In [61]:
a.argmin()

1

【c】`any`, `all`

`any` means when the sequence has at least **one** `True` or non-zero element, return `True`, otherwise return `False`

`all` means when the sequence elements are **all** `True` or non-zero elements, return `True`, otherwise return `False`

In [62]:
a = np.array([0,1])
a.any()

True

In [63]:
 a.all()

False

【d】`cumprod`, `cumsum`, `diff`

`cumprod` and `cumsum` represent cumulative multiplication and addition functions respectively, returning an array of the same length. `diff` represents the difference with the previous element. Since the first element is a missing value, the return length is the original array minus 1 in the default parameter case.

In [64]:
a = np.array([1,2,3])
a.cumprod()

array([1, 2, 6], dtype=int32)

In [65]:
a.cumsum()

array([1, 3, 6], dtype=int32)

In [66]:
np.diff(a)

array([1, 1])

【e】 Statistical functions

Common statistical functions include `max, min, mean, median, std, var, sum, quantile`, among which quantile calculation is a global method and therefore cannot be called through the `array.quantile` method:

In [67]:
target = np.arange(5)
target

array([0, 1, 2, 3, 4])

In [68]:
target.max()

4

In [69]:
np.quantile(target, 0.5) # 0.5分位数

2.0

However, for arrays containing missing values, the results they return are also missing values. If you need to skip missing values, you must use a `nan*` type function. The above-mentioned statistical functions have corresponding `nan*` functions.

In [70]:
target = np.array([1, 2, np.nan])
target

array([ 1.,  2., nan])

In [71]:
target.max()

nan

In [72]:
np.nanmax(target)

2.0

In [73]:
np.nanquantile(target, 0.5)

1.5

The covariance and correlation coefficient can be calculated using `cov, corrcoef` as follows:

In [74]:
target1 = np.array([1,3,5,9])
target2 = np.array([1,5,3,-9])
np.cov(target1, target2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [75]:
np.corrcoef(target1, target2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

Finally, we need to explain the `axis` parameter of the statistical function in the two-dimensional `Numpy` array. It can calculate the statistical characteristics under a certain dimension. When `axis=0`, the result is the statistical index of the column, and when `axis=1`, the result is the statistical index of the row:

In [76]:
target = np.arange(1,10).reshape(3,-1)
target

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
target.sum(0)

array([12, 15, 18])

In [78]:
target.sum(1)

array([ 6, 15, 24])

### 5. Broadcast mechanism

The broadcast mechanism is used to handle operations between two arrays of different dimensions. Here we only discuss the broadcast mechanism of arrays with no more than two dimensions.

[a] Operations on scalars and arrays

When a scalar and an array are operated, the scalar will automatically expand its size to the array size, and then perform element-by-element operations:

In [79]:
res = 3 * np.ones((2,2)) + 1
res

array([[4., 4.],
       [4., 4.]])

In [80]:
res = 1 / res
res

array([[0.25, 0.25],
       [0.25, 0.25]])

【b】Operations between two-dimensional arrays

When the dimensions of two arrays are exactly the same, use the operations of corresponding elements, otherwise an error will be reported, unless the dimension of one of the arrays is $m×1$ or $1×n$, then the dimension with $1$ will be expanded to the size of the corresponding dimension of the other array. For example, when performing element-by-element operations on a $1×2$ array and a $3×2$ array, the first array will be expanded to $3×2$, and the corresponding values ​​during the expansion will be assigned. However, it should be noted that if the dimension of the first array is $1×3$, then an error will be reported because the size of the second dimension does not match and is not $1$.

In [81]:
res = np.ones((3,2))
res

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [82]:
res * np.array([[2,3]]) # 第二个数组扩充第一维度为3

array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [83]:
res * np.array([[2],[3],[4]]) # 第二个数组扩充第二维度为2

array([[2., 2.],
       [3., 3.],
       [4., 4.]])

In [84]:
res * np.array([[2]]) # 等价于两次扩充，第二个数组两个维度分别扩充为3和2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

【c】Operation of one-dimensional array and two-dimensional array

When one-dimensional array $A_k$ is operated on two-dimensional array $B_{m,n}$, it is equivalent to treating the one-dimensional array as a two-dimensional array of $A_{1,k}$. The broadcasting rule used is the same as in 【b】. When $k!=n$ and $k,n$ are not $1$, an error is reported.

In [85]:
np.ones(3) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [86]:
np.ones(3) + np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [87]:
np.ones(1) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

### 6. Calculation of vectors and matrices
[a] Vector inner product: `dot`
$$\rm \mathbf{a}\cdot\mathbf{b} = \sum_ia_ib_i$$

In [88]:
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)

22

【b】Vector norm and matrix norm: `np.linalg.norm`

In the calculation of matrix norm, the most important parameter is `ord`, and the optional values ​​are as follows:

| ord | norm for matrices | norm for vectors |
| :---- | ----: | ----: |
| None | Frobenius norm | 2-norm |
| 'fro' | Frobenius norm | / |
| 'nuc' | nuclear norm | / |
| inf | max(sum(abs(x), axis=1)) | max(abs(x)) |
| -inf | min(sum(abs(x), axis=1)) | min(abs(x)) |
| 0 | / | sum(x != 0) |
| 1 | max(sum(abs(x), axis=0)) | as below |
| -1 | min(sum(abs(x), axis=0)) | as below |
| 2 | 2-norm (largest sing. value) | as below |
| -2 | smallest singularvalue | as below |
| other | / | sum(abs(x)\*\*ord)\*\*(1./ord) |

In [89]:
matrix_target =  np.arange(4).reshape(-1,2)
matrix_target

array([[0, 1],
       [2, 3]])

In [90]:
np.linalg.norm(matrix_target, 'fro')

3.7416573867739413

In [91]:
np.linalg.norm(matrix_target, np.inf)

5.0

In [92]:
np.linalg.norm(matrix_target, 2)

3.702459173643833

In [93]:
vector_target =  np.arange(4)
vector_target

array([0, 1, 2, 3])

In [94]:
np.linalg.norm(vector_target, np.inf)

3.0

In [95]:
np.linalg.norm(vector_target, 2)

3.7416573867739413

In [96]:
np.linalg.norm(vector_target, 3)

3.3019272488946263

【c】Matrix multiplication: `@`

$$\rm [\mathbf{A}_{m\times p}\mathbf{B}_{p\times n}]_{ij} = \sum_{k=1}^p\mathbf{A}_{ik}\mathbf{B}_{kj}$$

In [97]:
a = np.arange(4).reshape(-1,2)
a

array([[0, 1],
       [2, 3]])

In [98]:
b = np.arange(-4,0).reshape(-1,2)
b

array([[-4, -3],
       [-2, -1]])

In [99]:
a@b

array([[ -2,  -1],
       [-14,  -9]])

## 3. Exercises
### Ex1: Write matrix multiplication using list derivation
General matrix multiplication can be written by triple loops according to the formula. Please rewrite it in the form of list derivation.

In [100]:
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
res = np.empty((M1.shape[0],M2.shape[1]))
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item
(np.abs((M1@M2 - res) < 1e-15)).all() # 排除数值误差

True

### Ex2: Update matrix
Let matrix $A_{m×n}$ . Now update each element in $A$ to generate matrix $B$ . The update method is $B_{ij}=A_{ij}\sum_{k=1}^n\frac{1}{A_{ik}}$ . For example, if the matrix below is $A$ , then $B_{2,2}=5\times(\frac{1}{4}+\frac{1}{5}+\frac{1}{6})=\frac{37}{12}$ . Please use `Numpy` to implement it efficiently.
$$\begin{split}A=\left[ \begin{matrix} 1 & 2 &3\\4&5&6\\7&8&9 \end{matrix} \right]\end{split}$$

### Ex3: Chi-square statistic

Assume matrix $A_{m\times n}$, record $B_{ij} = \frac{(\sum_{i=1}^mA_{ij})\times (\sum_{j=1}^nA_{ij})}{\sum_{i=1}^m\sum_{j=1}^nA_{ij}}$, define the chi-square value as follows:
$$\chi^2 = \sum_{i=1}^m\sum_{j=1}^n\frac{(A_{ij}-B_{ij})^2}{B_{ij}}$$
Please use `Numpy` to calculate $\chi^2$ for the given matrix $A$

In [101]:
np.random.seed(0)
A = np.random.randint(10, 20, (8, 5))

### Ex4: Improve the performance of matrix calculation
Let $Z$ be a $m×n$ matrix, $B$ and $U$ be $m×p$ and $p×n$ matrices respectively, $B_i$ be the $i$th row of $B$, $U_j$ be the $j$th column of $U$, and define $\displaystyle R=\sum_{i=1}^m\sum_{j=1}^n\|B_i-U_j\|_2^2Z_{ij}$ as follows, where $\|\mathbf{a}\|_2^2$ represents the sum of the squares of the components of vector $a$, $\sum_i a_i^2$.

Someone is calculating the value of $R$ based on the following sample data. Please make full use of the functions in `Numpy` to improve the performance of this code based on this problem.

In [102]:
np.random.seed(0)
m, n, p = 100, 80, 50
B = np.random.randint(0, 2, (m, p))
U = np.random.randint(0, 2, (p, n))
Z = np.random.randint(0, 2, (m, n))
def solution(B=B, U=U, Z=Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i]-U[:,j])**2).sum()
            L_res.append(norm_value*Z[i][j])
    return sum(L_res)
solution(B, U, Z)

100566

### Ex5: Maximum length of consecutive integers

Input a `Numpy` array of integers and return the maximum length of a strictly increasing consecutive integer subarray in it. The positive direction refers to the increasing direction. For example, input \[1,2,5,6,7\], \[5,6,7\] is a consecutive integer subarray with the maximum length, so the output is 3; input \[3,2,1,2,3,4,6\], \[1,2,3,4\] is a consecutive integer subarray with the maximum length, so the output is 4. Please make full use of `Numpy`'s built-in functions to complete. (Hint: Consider using `nonzero, diff` functions)