# Appendix A: Introduction to PyTorch (Part 1)

## A.1 What is PyTorch

In [ ]:
import torch
# Display the version of PyTorch
print(torch.__version__)

2.0.1


In [ ]:
# Displays whether PyTorch is the GPU version, False indicates the CPU version, True indicates the GPU version
print(torch.cuda.is_available())

False


## A.2 Vector

### A.2.1 Scalars, vectors, matrices, and tensors

In [3]:
import torch
import numpy as np

# Create a 0-dimensional tensor with Python integers
tensor0d = torch.tensor(1)

# Create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# Create a 2D tensor (vector) using a Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])

# Create a 3D tensor using nested Python lists
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Create a 3D tensor from a NumPy array
ary3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor3d_2 = torch.tensor(ary3d)  # 复制NumPy数组
tensor3d_3 = torch.from_numpy(ary3d)  # 与NumPy数组共享内存

In [4]:
ary3d[0, 0, 0] = 999
print(tensor3d_2) # 保持不变

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [5]:
print(tensor3d_3) # 由于内存共享需要改变

tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


### A.2.2 Vector Data Types

In [6]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [7]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [8]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


### A.2.3 Common Tensor Operations in PyTorch

In [9]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
tensor2d.shape # 张量形状

torch.Size([2, 3])

In [11]:
tensor2d.reshape(3, 2) # 修改形状

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
tensor2d.view(3, 2) # 查看张量

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
tensor2d.T # 转置张量

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [14]:
tensor2d.matmul(tensor2d.T) # 张量乘法：tensor2d与其转置相乘

tensor([[14, 32],
        [32, 77]])

In [15]:
tensor2d @ tensor2d.T # 张量乘法的另一种实现方式：tensor2d与其转置相乘

tensor([[14, 32],
        [32, 77]])

## A.3 Model as a computational graph

In [16]:
import torch.nn.functional as F

y = torch.tensor([1.0])  # 真实样本
x1 = torch.tensor([1.1]) # 输入特征
w1 = torch.tensor([2.2]) # 权重变量
b = torch.tensor([0.0])  # 偏置单元

z = x1 * w1 + b          # 网络输入
a = torch.sigmoid(z)     # 激活函数 & 输出

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


## A.4 Automatic differentiation

In [17]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b 
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [18]:
loss.backward()# 反向传播

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


## A.5 Implementation of multi-layer neural network

In [19]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
                
# First hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

# Second hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

# Output layer
            torch.nn.Linear(20, num_outputs),
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [20]:
model = NeuralNetwork(50, 3)

In [21]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [22]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable model parameters:", num_params)# 打印训练模型的参数

Total number of trainable model parameters: 2213


In [23]:
print(model.layers[0].weight) # 打印神经网络模型的第一层的权重

Parameter containing:
tensor([[-0.0064,  0.0004, -0.0903,  ..., -0.1316,  0.0910,  0.0363],
        [ 0.1354,  0.1124, -0.0476,  ...,  0.0578,  0.1014,  0.0008],
        [ 0.0975, -0.0478,  0.0298,  ...,  0.0416,  0.0849,  0.1314],
        ...,
        [ 0.0118,  0.0240,  0.0420,  ..., -0.1305, -0.0517, -0.0826],
        [-0.0323,  0.1073,  0.0215,  ..., -0.1264, -0.1100,  0.1232],
        [ 0.0861,  0.0403, -0.0545,  ...,  0.1352,  0.0817, -0.0938]],
       requires_grad=True)


In [24]:
# Set the random number seed to ensure reproducibility
torch.manual_seed(123)

# Assume that NeuralNetwork is a neural network class, and its constructor accepts two parameters, the dimension of the input feature and the dimension of the output feature.
model = NeuralNetwork(50, 3)

# Print the weights of the first layer of the neural network model
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [25]:
# Print the shape of the first layer weights of the neural network model
print(model.layers[0].weight.shape)

torch.Size([30, 50])


In [26]:
# Set the random number seed to ensure reproducibility
torch.manual_seed(123)

# The dimension of the model input feature is 50
X = torch.rand((1, 50))

# Use the model to perform forward propagation calculation output
out = model(X)

# Print output results
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [27]:
# Use the torch.no_grad() context manager to not compute gradients at inference time
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [28]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3113, 0.3934, 0.2952]])


## A.6 Building an efficient data loader

In [29]:
# Define input feature tensor X_train
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

# Define the corresponding label tensor y_train
y_train = torch.tensor([0, 0, 0, 1, 1])

In [30]:
X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])

y_test = torch.tensor([0, 1])

In [31]:
from torch.utils.data import Dataset


class ToyDataset(Dataset):
# Initialize the ToyDataset class
    def __init__(self, X, y):
        self.features = X
        self.labels = y
# Get the data of the specified index
    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]        
        return one_x, one_y
# Get the length of the dataset
    def __len__(self):
        return self.labels.shape[0]
# Create training and testing dataset instances
train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [32]:
len(train_ds)

5

In [33]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

# Create a training data loader train_loader
# The dataset parameter passes in an instance of the ToyDataset class you defined, train_ds
# The batch_size parameter specifies the number of samples contained in each batch
# The shuffle parameter specifies whether to shuffle the data before each epoch
# The num_workers parameter specifies the number of subprocesses used for data loading
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)

In [34]:
test_ds = ToyDataset(X_test, y_test)

# Create a test data loader test_loader
# The dataset parameter passes in an instance of the ToyDataset class you defined test_ds
# The batch_size parameter specifies the number of samples contained in each batch
# The shuffle parameter specifies whether to shuffle the data before each epoch. Here, setting it to False means not to shuffle.
# The num_workers parameter specifies the number of subprocesses used for data loading
test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

In [35]:
# Iterate the training data loader train_loader
for idx, (x, y) in enumerate(train_loader):
# Print the index, input features and corresponding labels of each batch
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [36]:
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

In [ ]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

## A.7 An example training epoch

In [38]:
import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):
    
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)
        
        loss = F.cross_entropy(logits, labels) # 损失函数
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
### log
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
# Optional model evaluation metrics

Epoch: 001/003 | Batch 000/002 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 001/002 | Train/Val Loss: 0.65
Epoch: 002/003 | Batch 000/002 | Train/Val Loss: 0.44
Epoch: 002/003 | Batch 001/002 | Train/Val Loss: 0.13
Epoch: 003/003 | Batch 000/002 | Train/Val Loss: 0.03
Epoch: 003/003 | Batch 001/002 | Train/Val Loss: 0.00


In [39]:
model.eval()

with torch.no_grad():
    outputs = model(X_train)

print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [40]:
# Set PyTorch's printing options to turn off scientific notation
torch.set_printoptions(sci_mode=False)

# Assume outputs is the output tensor of the model

# Perform softmax operation on the output of the model to calculate the category probability
probas = torch.softmax(outputs, dim=1)
print(probas)

# Get the model's prediction result, that is, the category with the highest probability
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([[    0.9991,     0.0009],
        [    0.9982,     0.0018],
        [    0.9949,     0.0051],
        [    0.0491,     0.9509],
        [    0.0307,     0.9693]])
tensor([0, 0, 0, 1, 1])


In [41]:
# Use torch.argmax() function to get the index of the maximum value of each sample along dim=1 dimension, which is the prediction result of the model
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [42]:
predictions == y_train

tensor([True, True, True, True, True])

In [43]:
torch.sum(predictions == y_train)

tensor(5)

In [44]:
def compute_accuracy(model, dataloader):
    """
    计算模型在给定数据加载器上的准确率。

    参数：
        model (torch.nn.Module): 待评估的模型。
        dataloader (torch.utils.data.DataLoader): 包含输入数据的数据加载器。

    返回：
        float: 准确率值。
    """
# Set the model to evaluation mode
    model = model.eval()
    correct = 0.0
    total_examples = 0
    
# Iterate over the data loaders
    for idx, (features, labels) in enumerate(dataloader):
        
# Use no_grad context so that gradients are not tracked
        with torch.no_grad():
# Use the model to perform forward propagation to obtain prediction results
            logits = model(features)
        
# Get the prediction results and count the number of correct predictions
        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

# Calculate and return the accuracy
    return (correct / total_examples).item()

In [45]:
compute_accuracy(model, train_loader)

1.0

In [46]:
compute_accuracy(model, test_loader)

1.0

## A.8 Save and load the model

In [47]:
torch.save(model.state_dict(), "model.pth")

In [48]:
model = NeuralNetwork(2, 2) # 需要与原始模型完全匹配
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

## A.9 Using GPU to optimize training performance

### A.9.1 PyTorch operations on GPU

See [code-part2.ipynb](code-part2.ipynb)

### A.9.2 Training on a single GPU

See [code-part2.ipynb](code-part2.ipynb)

### A.9.3 Training with multiple GPUs

See [DDP-script.py](DDP-script.py)